use_frameworks!

platform :ios, '8.0'

target 'KYMultiScrollView_Example' do
  pod 'KYMultiScrollView', :path => '../'

  target 'KYMultiScrollView_Tests' do
    inherit! :search_paths

    
  end
end
